"""Conservative release inventory; not a measurement of Vercel-generated functions."""

import json
from pathlib import Path


def main():
    root = Path.cwd()
    paths = [
        root / name
        for name in (
            ".venv",
            "src",
            "deployment/generated-model",
            "results",
            "app.py",
            "pyproject.toml",
            "uv.lock",
            "vercel.json",
        )
    ]
    if not (root / "deployment/generated-model/network-hgb.joblib").is_file():
        raise ValueError("Missing release model")
    sizes = {}
    for path in paths:
        if not path.exists():
            raise ValueError("Missing release inventory input")
        sizes[path.name] = (
            sum(p.stat().st_size for p in path.rglob("*") if p.is_file())
            if path.is_dir()
            else path.stat().st_size
        )
    total = sum(sizes.values())
    # Leave room below the standard 500 MB Python allowance for generated glue,
    # runtime and provider-generated bytecode. Inspect the hosted output separately.
    budget = 450_000_000
    print(json.dumps({"inventory_bytes": total, "budget_bytes": budget, "components": sizes}))
    if total > budget:
        raise ValueError("Release inventory exceeds the conservative packaging budget")


if __name__ == "__main__":
    main()
